name: "Validations"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify-json-schem:
    name: "Verify json schema"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: "Install check-jsonschema"
        run: pip install check-jsonschema

      - name: "Verify overrides json schema"
        run: check-jsonschema --schemafile schema/overrides.schema.json data/**/*.json




  
